from __future__ import annotations

from typing import Any, Protocol


class LocatorLike(Protocol):
    @property
    def first(self) -> LocatorLike: ...

    def count(self) -> int: ...

    def click(self, **kwargs: Any) -> Any: ...


class PageLike(Protocol):
    @property
    def url(self) -> str: ...

    def goto(self, url: str, **kwargs: Any) -> Any: ...

    def content(self) -> str: ...

    def evaluate(self, expression: str, *args: Any) -> Any: ...

    def close(self) -> None: ...

    def wait_for_timeout(self, timeout: float | int) -> None: ...

    def wait_for_load_state(self, state: str, **kwargs: Any) -> Any: ...

    def fill(self, selector: str, value: str, **kwargs: Any) -> Any: ...

    def click(self, selector: str, **kwargs: Any) -> Any: ...

    def expect_download(self, **kwargs: Any) -> Any: ...

    def text_content(self, selector: str) -> str | None: ...

    def bring_to_front(self) -> None: ...

    def locator(self, selector: str) -> LocatorLike: ...

    def eval_on_selector(self, selector: str, expression: str, *args: Any, **kwargs: Any) -> Any: ...

    def eval_on_selector_all(self, selector: str, expression: str, *args: Any, **kwargs: Any) -> Any: ...

    def add_init_script(self, script: str, **kwargs: Any) -> Any: ...

    def go_back(self, **kwargs: Any) -> Any: ...


class APIRequestContextLike(Protocol):
    def post(self, url: str, **kwargs: Any) -> Any: ...


class BrowserContextLike(Protocol):
    @property
    def request(self) -> APIRequestContextLike: ...

    @property
    def pages(self) -> list[PageLike]: ...

    def new_page(self) -> PageLike: ...

    def storage_state(self, **kwargs: Any) -> Any: ...

    def close(self) -> None: ...

    def on(self, event: str, handler: Any) -> Any: ...

    def remove_listener(self, event: str, handler: Any) -> Any: ...
